version: '3'
services:
    web:
        image: nginx:alpine
        container_name: nginx-container
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./laravel:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}

        restart: always
        depends_on:
            - php
            - mysqldb
        networks:
            - code-network
            
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: php-container
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./laravel:/var/www/html"
        networks:
            - code-network

    composer:
        image: "composer"
        container_name: composer-container
        volumes:
            - "./laravel/:/app"
        command: install
        networks:
            - code-network

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql-container
        restart: always
        depends_on:
            - mysqldb
        networks:
            - code-network
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: mysql-container
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge 