version: '3'
services:
    php:
        image: php:fpm-alpine
        container_name: php
        volumes:
            - ./laravel:/var/www
        entrypoint:
            - php-fpm
        networks:
            - code-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./laravel:/var/www
            - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        ports:
            - 8080:80
        networks:
            - code-network

    mysql:
        image: mysql:5.7
        container_name: mysql57
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3305:3306

        env_file:
            - "./laravel/.env"
        environment: 
            MYSQL_USER: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: root12
            MYSQL_ROOT_PASSWORD: root
        networks:
            - code-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links: 
            - mysql
        ports:
            - 8000:80
        environment:
            PMA_HOST: mysql
        networks:
            - code-network

volumes:
    dbdata:

networks:
    code-network:
        driver: bridge